build image:
  tags:
    - ecgalaxy-image
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - IMAGE_NAME=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
    - IMAGE_TAG=$(git describe --tags --abbrev=0)-$(date "+%y%m%d%H%M%S")
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f Dockerfile .
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
    - docker push ${IMAGE_NAME}:latest
